version: '3'

volumes:
  nextcloud:
  db:
  redis:

services:
  db:
    image: mariadb:latest
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      # パスワードなので適宜変更する
      - MYSQL_ROOT_PASSWORD=test1234
      - MYSQL_PASSWORD=test1234
      ##############################
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

  app:
    #image: nextcloud:latest
    build:
      context: nextcloud/
      dockerfile: Dockerfile
    restart: always
    ports:
      - 443:443
      #- 8080:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      # パスワードなので適宜変更する
      - MYSQL_PASSWORD=test1234
      ##############################
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis
  
  cron:
    build:
      context: nextcloud/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - app